version: '3.5'

services:
  lint:
    image: golangci/golangci-lint:v1.54.1
    working_dir: /app
    volumes:
      - ..:/app
      - ~/.cache/golangci-lint/v1.54.1:/root/.cache
    command:
      - golangci-lint
      - run
  release:
    image: goreleaser/goreleaser:v1.20.0
    working_dir: /go/src/github.com/buildkite/cli
    volumes:
      - .:/go/src/github.com/buildkite/cli
