env:
  GLOBAL_ENV: llamas
  ENV_ORDER: global

steps:
  - label: "hello world"
    command: echo hello world

  - label: "test env"
    env:
      - LOCAL_ENV=alpacas
      - ENV_ORDER=local
    command: |
      [[ "\${GLOBAL_ENV?}" == "llamas" ]]
      [[ "\${LOCAL_ENV?}" == "alpacas" ]]
      [[ "\${ENV_ORDER?}" == "local" ]]

  - label: "set metadata"
    command: |
      buildkite-agent meta-data set "family" "camelids"
      buildkite-agent meta-data set "size" "large"

  - wait
  - label: "get metadata"
    command: |
      buildkite-agent meta-data exists "family"
      family=$(buildkite-agent meta-data get "family")
      [[ \${family} == "camelids" ]]

  - label: "list metadata keys"
    command: |
      keys=$$(buildkite-agent meta-data keys | tr "\n" ",")
      [[ \${keys} == "family,size," ]]

  - wait

  - label: upload relative artifact
    command: |
      set -Eeufo pipefail

      trap "rm llamas.txt" EXIT

      echo "relative llamas" > llamas.txt
      buildkite-agent artifact upload llamas.txt

      shasum=$(buildkite-agent artifact shasum llamas.txt)
      expected_shasum=fb60f84c2bd316e18a2f11e4da13684e41a16f31
      if [[ \$shasum != \$expected_shasum ]]; then
        echo expected: \$expected_shasum received: \$shasum
        exit 1
      fi

  - label: upload absolute artifact
    command: |
      set -Eeufo pipefail

      trap "rm /tmp/llamas.txt" EXIT

      echo "absolute llamas" > /tmp/llamas.txt
      buildkite-agent artifact upload /tmp/llamas.txt

      shasum=$(buildkite-agent artifact shasum tmp/llamas.txt)
      expected_shasum=9ce999892fbca0da31b2a781b2730ac11a2fc8a2
      if [[ \$shasum != \$expected_shasum ]]; then
        echo expected: \$expected_shasum received: \$shasum
        exit 1
      fi

  - wait

  - label: download relative artifact
    command: |
      set -Eeufo pipefail

      trap "rm llamas.txt" EXIT

      buildkite-agent artifact download llamas.txt .
      echo "ee756d1e307dc245b0df42f81845a4ff559531bc4cb287e35b15e4115844e903 llamas.txt" | sha256sum --check

  - label: download absolute artifact
    command: |
      set -Eeufo pipefail

      trap "rm tmp/llamas.txt" EXIT

      buildkite-agent artifact download tmp/llamas.txt .
      echo "e14227c78a206decdf9e869aaa2c44f3ff546a8324874e7442ef02b1f41a0099 tmp/llamas.txt" | sha256sum --check
